### ISSUE TITLE
Question regarding LLaMA-3.1 LongBench score

### ISSUE THREAD

**Issue by MarsJacobs** [SalesforceAIResearch/GemFilter#2]
Hi, thank you for sharing such great work! I’ve learned a lot from it.

I wanted to ask about something regarding Main Table 1 of the paper, where the performance of LLaMA-3.1-8B-Instruct on LongBench seems to underperform. For reference, when I measured the performance of LLaMA-3.1-8B-instruct, I obtained an overall average of around 49. Specifically, the performance gap seems most noticeable in the QA tasks. Addressing this might make the comparison between your proposed method, All KV, and the baseline more clear.
(fyi, for qasper/MF-en/HotpotQA - 45.25/55.61/56 in my experiments, 13.04/27.34/16.23 in GemFilter)

In the code, particularly in this section:
https://github.com/SalesforceAIResearch/GemFilter/blob/5f79b1a15b4b281ddfc5d423009915eeab257d97/eval/LongBench/pred.py#L29

It seems like the chat template for LLaMA-3.1 is not being explicitly set. From my experience, using the [official chat template](https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct) as recommended in the LLaMA-3.1 documentation significantly improves performance, especially for QA tasks.

I hope my comment is helpful. 

(I really appreciate the straightforwardness of the proposed idea in the paper, which seems like a great way to alleviate the painful stress on prefill operations. Especially, finding filter layers with NIH seems novel and very practical method! )

**Comment by zhmeishi** [comment]
Hi MarsJacobs, 

We are so glad that you like our work. Yes, we have not used the official chat template, as recommended in LLaMA-3.1. Thank you for pointing this out! We have put this in our TODO list and will update our results with the official chat template in the next revision. Thanks!
